  name: Ejecutar acciones controladas en AWS desde Github Actions
  on:
    push:
      branches:
        - main


  env:
    AWS_ROLE: arn:aws:iam::755990962817:role/github-actions-oidc-role

  jobs:
    mango-dapp-job:
      runs-on: ubuntu-latest
      permissions:
        id-token: write

      steps:
        -  name: Configure AWS credentials from OIDC
           uses: aws-actions/configure-aws-credentials@v4
           with:
             role-to-assume: ${{ env.AWS_ROLE }}
             aws-region: us-east-2
             
        -  name: Run AWS CLI commands
           run:  |
             # Crear ECS Cluster
             aws ecs create-cluster --cluster-name mango-dapp-ecs-cluster
    
